project:
  name: lab02-cloudformation-validation
  owner: <your-github-username>
  regions:
    - ap-southeast-1
  parameters:
    KeyName: lab02-keypair
    AllowedSSHIP: 0.0.0.0/0
tests:
  main-stack-test:
    template: main-cfn.yaml
    regions:
      - ap-southeast-1
    parameters:
      KeyName: lab02-keypair
      AllowedSSHIP: 0.0.0.0/0
