project:
  name: "lab02-cloudformation-validation"
  owner: cloud_user
  regions:
    - us-east-1
  s3_bucket: lab02-group18-bucket
tests:
  main-stack-test:
    template: main-cfn.yaml
    regions:
      - us-east-1
    parameters:
      KeyName: lab02-group18-keypair
      AllowedSSHIP: 0.0.0.0/0
      TempBucketFolder: lab02-cloudformation-validation/
