project:
  name: lab02-cloudformation-validation
  owner: FhuAnn
  regions:
    - ap-southeast-1

tests:
  main-stack-test:
    template: main-cfn.yaml
    regions:
      - ap-southeast-1
    parameters:
      KeyName: lab02-keypair-group18
      AllowedSSHIP: 0.0.0.0/0
    cleanup: true
