version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.9
      docker: 20
    commands:
      - pip install --upgrade pip
      - pip install --upgrade cfn-lint taskcat
  build:
    commands:
      - echo "Checking template syntax with cfn-lint"
      - cfn-lint *.yaml templates/*.yaml
      - echo "Checking template syntax with taskcat lint"
      - taskcat lint
      - echo "Packaging and uploading templates to S3 with taskcat package"
      - taskcat package --s3-bucket an-03042004-bucket
      - echo "Running taskcat test run"
      - taskcat test run
artifacts:
  files:
    - '**/*'
  discard-paths: yes