version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.9
    commands:
      - pip install --upgrade pip
      - pip install --upgrade cfn-lint taskcat
      - aws configure set region us-east-1
      - export AWS_DEFAULT_REGION=us-east-1 # Đặt biến môi trường
  build:
    commands:
      - echo "Checking template syntax with cfn-lint"
      - cfn-lint *.yaml templates/*.yaml
      - echo "Checking template syntax with taskcat lint"
      - taskcat lint
      - echo "Packaging and uploading templates to S3 with taskcat package"
      - taskcat package
      - echo "Running taskcat test run"
      - taskcat test run
  post_build:
    commands:
      - echo "Uploading templates to S3"
      - aws s3 cp templates/vpc-cfn.yaml s3://lab02-group18-bucket/templates/vpc-cfn.yaml
      - aws s3 cp templates/nat-cfn.yaml s3://lab02-group18-bucket/templates/nat-cfn.yaml
      - aws s3 cp templates/ec2-cfn.yaml s3://lab02-group18-bucket/templates/ec2-cfn.yaml
      - aws s3 cp templates/rt-cfn.yaml s3://lab02-group18-bucket/templates/rt-cfn.yaml
      - aws s3 cp templates/sg-cfn.yaml s3://lab02-group18-bucket/templates/sg-cfn.yaml
      - aws s3 cp main-cfn.yaml s3://lab02-group18-bucket/main-cfn.yaml
      - echo "Deploying CloudFormation stack"
      - aws cloudformation deploy --template-file main-cfn.yaml --stack-name lab02-group18-main --region us-east-1 --capabilities CAPABILITY_IAM CAPABILITY_NAMED_IAM
artifacts:
  files:
    - "**/*"
  discard-paths: yes
