Resources:
  TaskcatBuildProject:
    Type: AWS::CodeBuild::Project
    Properties:
      Name: taskcat-build
      Source:
        Type: CODEPIPELINE
        BuildSpec: buildspec.yml
      Environment:
        Type: LINUX_CONTAINER
        Image: aws/codebuild/standard:7.0
        ComputeType: BUILD_GENERAL1_SMALL
        PrivilegedMode: true
      ServiceRole: arn:aws:iam::072461344223:role/CodeBuildServiceRole
      Artifacts:
        Type: CODEPIPELINE
