Resources:
  TaskcatPipeline:
    Type: AWS::CodePipeline::Pipeline
    Properties:
      Name: taskcat-pipeline
      RoleArn: arn:aws:iam::654654274227:role/CodePipelineServiceRole
      ArtifactStore:
        Type: S3
        Location: lab02-group18-bucket
      Stages:
        - Name: Source
          Actions:
            - Name: Source
              ActionTypeId:
                Category: Source
                Owner: AWS
                Provider: CodeCommit
                Version: "1"
              Configuration:
                RepositoryName: NT548-Practice02-Group18-P2-CloudFormation-CodePipeline-hello
                BranchName: master
              OutputArtifacts:
                - Name: SourceArtifact
        - Name: Build
          Actions:
            - Name: Build
              ActionTypeId:
                Category: Build
                Owner: AWS
                Provider: CodeBuild
                Version: "1"
              Configuration:
                ProjectName: taskcat-build
              InputArtifacts:
                - Name: SourceArtifact
              OutputArtifacts:
                - Name: BuildArtifact
