Resources:
  TaskcatPipeline:
    Type: AWS::CodePipeline::Pipeline
    Properties:
      Name: taskcat-pipeline
      RoleArn: arn:aws:iam::072461344223:role/CodePipelineServiceRole
      ArtifactStore:
        Type: S3
        Location: an-ho-bucket
      Stages:
        - Name: Source
          Actions:
            - Name: Source
              ActionTypeId:
                Category: Source
                Owner: AWS
                Provider: CodeStarSourceConnection
                Version: "1"
              Configuration:
                ConnectionArn: arn:aws:codeconnections:ap-southeast-1:072461344223:connection/c0c2b49c-b351-4b11-93bc-3db614baa298
                FullRepositoryId: FhuAnn/NT548-Practice02-Group18-P2-CloudFormation-CodePipeline
                BranchName: main
                DetectChanges: true
              OutputArtifacts:
                - Name: SourceArtifact
        - Name: Build
          Actions:
            - Name: Build
              ActionTypeId:
                Category: Build
                Owner: AWS
                Provider: CodeBuild
                Version: "1"
              Configuration:
                ProjectName: taskcat-build
              InputArtifacts:
                - Name: SourceArtifact
              OutputArtifacts:
                - Name: BuildArtifact
