AWSTemplateFormatVersion: 2010-09-09
Description: This template create Nested stack

Parameters:
  AllowedSSHIP:
    Description: The IP address allowed to SSH to the public EC2 instances
    Type: String
    Default: 0.0.0.0/0 # Change to your user IP address

  KeyName:
    Description: Name of an existing EC2 KeyPair to enable SSH access to the instances
    Type: AWS::EC2::KeyPair::KeyName
    Default: lab02-group18-keypair # Change to your key pair name

  InstanceType:
    Description: EC2 instance type
    Type: String
    Default: t2.micro
    AllowedValues:
      - t2.micro
      - t2.small
      - t2.medium

  SubTemplatePath:
    Type: String
    Default: ""
    Description: Folder store temp templates

Resources:
  VPCStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: !Sub https://lab02-group18-bucket.s3.us-east-1.amazonaws.com/${SubTemplatePath}templates/vpc-cfn.yaml
      TimeoutInMinutes: 10

  NATStack:
    Type: AWS::CloudFormation::Stack
    DependsOn: VPCStack
    Properties:
      TemplateURL: !Sub https://lab02-group18-bucket.s3.us-east-1.amazonaws.com/lab02-cloudformation-validation/${SubTemplatePath}templates/nat-cfn.yaml
      TimeoutInMinutes: 10

  RouteTablesStack:
    Type: AWS::CloudFormation::Stack
    DependsOn:
      - VPCStack
      - NATStack
    Properties:
      TemplateURL: !Sub https://lab02-group18-bucket.s3.us-east-1.amazonaws.com/lab02-cloudformation-validation/${SubTemplatePath}templates/rt-cfn.yaml
      TimeoutInMinutes: 10

  SecurityGroupsStack:
    Type: AWS::CloudFormation::Stack
    DependsOn: VPCStack
    Properties:
      TemplateURL: !Sub https://lab02-group18-bucket.s3.us-east-1.amazonaws.com/lab02-cloudformation-validation/${SubTemplatePath}templates/sg-cfn.yaml
      TimeoutInMinutes: 10
      Parameters:
        AllowedSSHIP: !Ref AllowedSSHIP

  EC2Stack:
    Type: AWS::CloudFormation::Stack
    DependsOn:
      - VPCStack
      - RouteTablesStack
      - SecurityGroupsStack
    Properties:
      TemplateURL: !Sub https://lab02-group18-bucket.s3.us-east-1.amazonaws.com/lab02-cloudformation-validation/${SubTemplatePath}templates/ec2-cfn.yaml
      TimeoutInMinutes: 10
      Parameters:
        KeyName: !Ref KeyName
        InstanceType: !Ref InstanceType

Outputs:
  PublicInstanceIP:
    Description: Public IP address of the Public Instance
    Value: !GetAtt EC2Stack.Outputs.PublicInstanceIP

  PrivateInstancePrivateIP:
    Description: Private IP address of the Private Instance
    Value: !GetAtt EC2Stack.Outputs.PrivateInstancePrivateIP
